### ISSUE TITLE
Page numbers do not show up

### ISSUE THREAD

**Issue by ChampiYann** [TUDSSL/TUD_ENS_MSc_Thesis_Template#3] opened 2019-11-19 08:34 UTC
When compiling, the page numbers are not shown except on the first page of a chapter.
This is caused by the the `\pagestyle{empty}` command in the quotation.tex file.
I think this command should be `\thispagestyle{empty}`.

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 08:37
Feel free to do a pull request on this

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 08:38
However, I cannot reproduce this behavior. The latest thesis that I got from a student using this template had all page numbers correct.

**Comment by ChampiYann** [comment] 2019-11-19 09:09
Without changing anything to the template, this is what I get. 
[thesis.pdf](https://github.com/TUDSSL/TUD_ENS_MSc_Thesis_Template/files/3862882/thesis.pdf)
If you have a look at chapter 2, the second page has no page number.

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 09:15
I think this is because these chapters are empty. Please fill them in with some random text and see if you still cannot see the page numbers.

**Comment by ChampiYann** [comment] 2019-11-19 09:21
This is with added blindtext.
[thesis.pdf](https://github.com/TUDSSL/TUD_ENS_MSc_Thesis_Template/files/3862944/thesis.pdf)
The exact same happens with my own thesis, unless I change the code mentioned in the first comment

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 09:29
OK then please push the change to the repo and I will review it. Thanks!

**Comment by ChampiYann** [comment] 2019-11-19 09:33
Will do, but git returns a Permission denied error when I try to push my branch. 
`remote: Permission to TUDSSL/TUD_ENS_MSc_Thesis_Template.git denied to ChampiYann.`
`fatal: unable to access 'https://github.com/TUDSSL/TUD_ENS_MSc_Thesis_Template.git/': The requested URL returned error: 403`
Is everyone allowed to contribute?

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 09:36
Probably because it is hosted within my research team git. Can you send me the code snippet whan should I change, then I can change it directly? Thanks!

**Comment by ChampiYann** [comment] 2019-11-19 09:40
I think this should be the entire code of the quotation.tex file

```
\thispagestyle{empty}

\null\vfill

\begin{center}
\emph{``WRITE YOUR QUOTE HERE''} -- WRITE THE NAME OF THE AUTHOR OF THE QUOTE HERE
\end{center}

\vspace{10cm}

\clearpage
```

Essentially the first line changes from `\pagestyle{empty}` to `\thispagestyle{empty}`

**Comment by przemyslaw-pawelczak** [comment] 2019-11-19 10:35
Done. Thanks for help. Closing the issue

**Closed as completed by przemyslaw-pawelczak** 2019-11-19 10:35 UTC
